<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Fhir.Domain\Fhir.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hl7.Fhir.R4" Version="6.6.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
